def rules():
    print("*Introduction")
    print()
    print("Omi is a popular card game played in Sri Lanka: in some regins it is known as Oombi. Omi is a straightforward partnership plain-trick game of the Whist type, somewhat similar to the Indian and Pakistani game Court Piece in that the first player has to choose trumps on the basis of a the first few cards.")
    print()
    print()
    print("*Players and Cards")
    print()
    print("There are two players,one human and another as Robot")
    print("A standard international 52-card pack is used, but only 32 of the cards are used for play. These cards rank from high to low A-K-Q-J-10-9-8-7 in each suit.")
    print()
    print()
    print("*Deal and Making Trumps")
    print()
    print("Any player may deal first, and the turn to deal passes to the next player.")
    print("The program shuffles the 32-card pack and offers the eight cards to both players.")
    print("After the player receives 4 cards, analyzing the available rank and suits, the player announce which suit will be trumps. After announcing trump suit, the next 4 cards will be handed over and the game starts")
    print()
    print()
    print("*Play")
    print()
    print("The opposite player who did not announce the trump suit, leads any card to the first trick. Then the next player, and must follow suit if able to; a player who holds no card of the suit led may play any card. If no trumps are played, the trick is won by the highest card of the suit that was led. If any trumps were played the highest trump wins the trick.")
    print()
    print()
    print("*Scoring")
    print()
    print("Winner of the each trick will receive +2 and lead the next trick. Whoever has the highest score at the end of 8 tricks/ whole round will be the winner of the game.")
    print()
    print()
    print("*Tactics")
    print()
    print("When choosing trumps, one should select the suit in which one has most cards. Between two equal suits one of which contains the ace, it is better to make the other suit trumps, since the ace is likely to win a trick whether it is a trump or not. It is difficult to choose trump when holding cards of different suits - essentially one has to trust to luck. Some players pick the suit of the lowest card in this situation. Some players, holding four cards in three suits, with two low cards in one suit, will choose as trumps the suit in which they have no cards, hoping either to get trumps in the second part of the dea")
    print()
    print()
    print("*How robot takes the trump")
    print()
    print("When there is 2 cards in each suit, if one suit have ace, the one without ace will be taken as the trump. If there is no ace, the trump will be the suits with lower levels")
    print("When there is 3 cards in one suit and 1 card in another, the suit with 3 cards will be the trump ")
    print("When there is 4 different suits, suit with lowest level will be taken as the trump")
    print("When  holding 4 cards in 3 suits, with two low cards in one suit, will choose as trumps the suit in which they have no cards")
    print("When holding 2 cards in 2 suits and 2 cards in same suit, the suit with 2 cards will be the trump.")

